[tool.poetry]
name = "homework12"
version = "0.1.0"
description = ""
authors = ["Ivan Piankov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiokafka = "^0.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
